`include "decode_slice_if.sv"
`include "decode_slice_ref_model.sv"
`include "decode_slice_driver.sv"
`include "decode_slice_monitor.sv"
`include "decode_slice_scoreboard.sv"
`include "decode_slice_env.sv"
